# Generated by Django 3.2.6 on 2021-08-24 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=250)),
                ('speed', models.DecimalField(decimal_places=3, max_digits=3)),
                ('avg_speed', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fuel_level', models.DecimalField(decimal_places=3, max_digits=3)),
                ('engine_status', models.CharField(max_length=250)),
                ('camera1', models.CharField(blank=True, max_length=250)),
                ('camera2', models.CharField(blank=True, max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
