# Generated by Django 3.2.6 on 2021-08-24 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210825_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
